import path from 'path'
import { ColumnDefinition, KnexSchema, TableDefinition } from '../dsl'
import { writeTextFile } from '../utils/files'
import { columnName, pascalCase, tableName, typeName } from './names'

export function writeGeneratedTypes(schema: KnexSchema, baseDir: string) {
  const outputDir = path.resolve(baseDir, schema.generator.output)
  const typesFile = schema.generator.typesFile ?? 'types.ts'
  const knexTypesFile = schema.generator.knexTypesFile ?? 'knex-tables.d.ts'

  writeTextFile(path.join(outputDir, typesFile), generateTypes(schema))
  writeTextFile(path.join(outputDir, knexTypesFile), generateKnexTableAugmentation(schema, typesFile))
}

export function generateTypes(schema: KnexSchema) {
  const chunks: string[] = [
    '/* eslint-disable */',
    '// This file is generated by knexty. Do not edit manually.',
    "import type { Knex } from 'knex'",
    '',
    'export type JsonPrimitive = string | number | boolean | null',
    'export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue }',
    '',
  ]

  for (const enumDefinition of Object.values(schema.enums)) {
    const enumTypeName = pascalCase(enumDefinition.name)
    chunks.push(`export const ${enumTypeName} = {`)
    for (const value of enumDefinition.values) {
      chunks.push(`  ${value}: '${value}',`)
    }
    chunks.push(`} as const`)
    chunks.push(
      `export type ${enumTypeName} = typeof ${enumTypeName}[keyof typeof ${enumTypeName}]`,
      '',
    )
  }

  for (const table of Object.values(schema.tables)) {
    chunks.push(renderRowType(schema, table))
    chunks.push(renderInsertType(schema, table))
    chunks.push(renderUpdateType(schema, table))
  }

  chunks.push('export interface DatabaseTables {')
  for (const table of Object.values(schema.tables)) {
    const row = typeName(table.modelName, 'Row')
    const insert = typeName(table.modelName, 'Insert')
    const update = typeName(table.modelName, 'Update')
    chunks.push(
      `  '${tableName(table)}': Knex.CompositeTableType<${row}, ${insert}, ${update}>`,
    )
  }
  chunks.push('}', '')

  return `${chunks.join('\n')}\n`
}

export function generateKnexTableAugmentation(schema: KnexSchema, typesFile: string) {
  const typeExports = Object.values(schema.tables)
    .flatMap((table) => [
      typeName(table.modelName, 'Insert'),
      typeName(table.modelName, 'Row'),
      typeName(table.modelName, 'Update'),
    ])
    .join(', ')

  const chunks = [
    '/* eslint-disable */',
    '// This file is generated by knexty. Do not edit manually.',
    "import type { Knex } from 'knex'",
    `import type { ${typeExports} } from './${typesFile.replace(/\.ts$/, '')}'`,
    '',
    "declare module 'knex/types/tables' {",
    '  interface Tables {',
  ]

  for (const table of Object.values(schema.tables)) {
    const row = typeName(table.modelName, 'Row')
    const insert = typeName(table.modelName, 'Insert')
    const update = typeName(table.modelName, 'Update')
    chunks.push(
      `    '${tableName(table)}': Knex.CompositeTableType<${row}, ${insert}, ${update}>`,
    )
  }

  chunks.push('  }', '}', '', 'export {}', '')
  return chunks.join('\n')
}

function renderRowType(schema: KnexSchema, table: TableDefinition) {
  const lines = [`export interface ${typeName(table.modelName, 'Row')} {`]
  for (const column of Object.values(table.columns)) {
    lines.push(`  ${propertyName(columnName(column))}: ${readType(schema, column)}`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

function renderInsertType(schema: KnexSchema, table: TableDefinition) {
  const lines = [`export interface ${typeName(table.modelName, 'Insert')} {`]
  for (const column of Object.values(table.columns)) {
    const optional = column.generated || column.defaultValue || column.nullable ? '?' : ''
    lines.push(`  ${propertyName(columnName(column))}${optional}: ${insertType(schema, column)}`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

function renderUpdateType(schema: KnexSchema, table: TableDefinition) {
  const lines = [`export interface ${typeName(table.modelName, 'Update')} {`]
  for (const column of Object.values(table.columns)) {
    lines.push(`  ${propertyName(columnName(column))}?: ${insertType(schema, column)}`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

function propertyName(name: string) {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `'${name}'`
}

function readType(schema: KnexSchema, column: ColumnDefinition) {
  const base = scalarType(schema, column, 'read')
  return column.nullable ? `${base} | null` : base
}

function insertType(schema: KnexSchema, column: ColumnDefinition) {
  const base = scalarType(schema, column, 'write')
  return column.nullable ? `${base} | null` : base
}

function scalarType(schema: KnexSchema, column: ColumnDefinition, mode: 'read' | 'write'): string {
  switch (column.type) {
    case 'bigint':
    case 'bigInteger':
      return 'string'
    case 'binary':
      return 'Buffer'
    case 'boolean':
      return 'boolean'
    case 'date':
    case 'dateTime':
    case 'timestamp':
      return 'Date'
    case 'decimal':
      return mode === 'read' ? 'string' : 'string | number'
    case 'double':
      return 'number'
    case 'enum':
      return column.enumName
        ? pascalCase(findEnumDefinition(schema, column.enumName)?.name ?? column.enumName)
        : 'string'
    case 'enu':
      return column.enumValues?.length
        ? column.enumValues.map((value) => JSON.stringify(value)).join(' | ')
        : 'string'
    case 'float':
    case 'integer':
    case 'tinyint':
    case 'smallint':
    case 'mediumint':
    case 'bigIncrements':
    case 'increments':
    case 'serial':
      return 'number'
    case 'json':
    case 'jsonb':
      return 'JsonValue'
    case 'jsonbArray':
      return 'JsonValue[]'
    case 'geography':
    case 'geometry':
    case 'point':
    case 'specificType':
      return 'unknown'
    case 'string':
    case 'text':
    case 'uuid':
      return 'string'
    case 'textArray':
      return 'string[]'
    case 'time':
      return 'string'
    default:
      return 'unknown'
  }
}

function findEnumDefinition(schema: KnexSchema, name: string) {
  return schema.enums[name] ?? Object.values(schema.enums).find((item) => item.name === name)
}
